# This Censorship Distribution Helper is used to generate the gganimate plot of
# the time distribution of censorship in the last page of the Shiny application.
# The file takes in an RDS file containing the time distribution and transforms
# it into a plot. The RDS file is generated in the Pipeline Helper File through
# Apache Spark.

# Libraries ------------------------------------------------------------------

library(tidyverse)
library(stringr)
library(gganimate)
library(lubridate)

# Loading Data ----------------------------------------------------------------
# Reading the RDS file generated by the pipeline_helper.R file for processing.

permission_denied_dist <- read_rds("weibo_air_quality/data/permission_denied_dist.rds")

# Plot Creation ---------------------------------------------------------------

censorship_dist_plot <- permission_denied_dist %>%
  ggplot(aes(x = created_date, y = deleted_count)) +

  # Change the color of the line to red for aesthetic effect.

  geom_line(color = "#d11141") +

  # gganimate: creation of the animated plot.

  transition_reveal(created_date) +
  theme_minimal() +
  labs(
    title = "Tightening the Grip",
    subtitle = "Number of recorded censorship on the rise in 2012.",
    x = NULL,
    y = "Number of Monitored Censored Posts",
    caption = "Source: Open WeiboScope/Hong Kong University"
  ) +

  # To avoid disturbing aesthetic effect, we set the minor grid element to blank.

  theme(panel.grid.minor = element_blank()) +
  theme(
    plot.title = element_text(
      family = "Georgia",
      size = 20
    ),
    plot.subtitle = element_text(size = 15)
  )

# Code to animate the distribution plot. Parameters optimized for browser display.

animate(censorship_dist_plot,
  nframes = 365,
  fps = 30,
  duration = 10,
  end_pause = 150,
  width = 800,
  height = 400
)

anim_save("weibo_air_quality/www/censorship_dist_plot.gif",
  animation = censorship_dist_plot,
  nframes = 365,
  fps = 30,
  duration = 10,

  # We do not want the plot to stop immediately after it completes the
  # animation. We wait for 150 frames after the plot restarts itself.

  end_pause = 150,
  width = 800,
  height = 400
)
